### ISSUE TITLE
Fix comment contrast

### ISSUE THREAD

**Issue by StefKors** [StefKors/Hyperlink-Nova-Theme#1]
![Screenshot 2020-04-27 at 10 03 48](https://user-images.githubusercontent.com/11800807/80348652-688be480-886e-11ea-8864-b423a2570ca4.png)

**Comment by 1Ale** [comment]
Hi. Maybe swap the comment color and the invisible color, I think invisible characters should be less noticeable than the comments.
<img width="569" alt="Captura de Tela 2020-06-01 às 11 11 18" src="https://user-images.githubusercontent.com/8279473/83417915-1c960780-a3f9-11ea-87a9-e83ea4b73b71.png">

**Comment by StefKors** [comment]
@1Ale Thanks for using the theme. I think your suggestion is a good one, I'll try to send an update soon. 

Feel free to send in a PR

**Comment by StefKors** [comment]
@1Ale The extension has been updated. You should be able to update from the extension library
